---
name: CD
"on":
  push:
  workflow_dispatch:

jobs:
  release:
    permissions:
      id-token: write
      packages: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Get go version
        id: go-version
        run: echo "name=version::$(go env GOVERSION)" >> $GITHUB_OUTPUT
      - name: Place wintun.dll
        run: cp -r deps/wintun/bin/amd64/wintun.dll ./
      - name: generate release notes
        run: |
          mkdir -p ./tmp
          ./scripts/changelog.sh > ./tmp/changelog.txt
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --release-notes=./tmp/changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload checksums as artifact
        uses: actions/upload-artifact@v2
        with:
          name: checksums
          path: dist/checksums.txt
